# Generated by Django 2.1.4 on 2018-12-08 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('lId', models.AutoField(primary_key=True, serialize=False)),
                ('lName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('mId', models.AutoField(primary_key=True, serialize=False)),
                ('mName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'metrics',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('wId', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.IntegerField(max_length=10)),
                ('wDate', models.DateField()),
                ('locationsId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WeatherApp.Locations')),
                ('metricsId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WeatherApp.Metrics')),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
