# Generated by Django 2.1.4 on 2018-12-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeatherApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='value',
        ),
        migrations.AddField(
            model_name='weather',
            name='wValue',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
